/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package team1.view;

import java.awt.Color;
import java.awt.Cursor;
import java.awt.Dimension;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.io.File;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JPasswordField;
import javax.swing.JTextField;
import team1.controller.UserController;
import team1.resources.ConfigApp;

/**
 *
 * @author bayug
 */
public class Login extends javax.swing.JFrame {
    private boolean showPass = false;
    UserController uc;
    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
        this.setBackground(new Color(0,0,0,0));
        uc = new UserController(this);
    }

    public JPasswordField getTxtPass() {
        return txtPass;
    }

    public JTextField getTxtUname() {
        return txtUname;
    }
    
    
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtUname = new javax.swing.JTextField();
        jSeparator1 = new javax.swing.JSeparator();
        jLabel3 = new javax.swing.JLabel();
        txtPass = new javax.swing.JPasswordField();
        eye = new javax.swing.JLabel();
        jSeparator2 = new javax.swing.JSeparator();
        txtMasuk = new javax.swing.JLabel();
        txtBtnExit = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Username");
        jPanel2.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 300, -1, -1));

        txtUname.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtUname.setForeground(new java.awt.Color(204, 204, 204));
        txtUname.setBackground(new Color(0,0,0,0));
        txtUname.setText("dev");
        txtUname.setBorder(null);
        txtUname.setOpaque(false);
        txtUname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtUnameKeyPressed(evt);
            }
        });
        jPanel2.add(txtUname, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 320, 230, -1));

        jSeparator1.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 340, 230, 10));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 0, 12)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Password");
        jPanel2.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 380, -1, -1));

        txtPass.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        txtPass.setForeground(new java.awt.Color(204, 204, 204));
        txtPass.setBackground(new Color(0,0,0,0));
        txtPass.setText("1");
        txtPass.setEchoChar('\u25cf');
        txtPass.setBorder(null);
        txtPass.setOpaque(false);
        txtPass.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtPassKeyPressed(evt);
            }
        });
        jPanel2.add(txtPass, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 400, 200, -1));

        eye.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        eye.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team1/image/iconEyeHide.png"))); // NOI18N
        eye.setToolTipText("Show");
        eye.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                eyeMouseClicked(evt);
            }
        });
        jPanel2.add(eye, new org.netbeans.lib.awtextra.AbsoluteConstraints(250, 400, -1, -1));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jPanel2.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 420, 230, 10));

        txtMasuk.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        txtMasuk.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team1/image/imgBLogin.png"))); // NOI18N
        txtMasuk.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtMasukMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtMasukMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtMasukMouseExited(evt);
            }
        });
        jPanel2.add(txtMasuk, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 450, -1, -1));

        txtBtnExit.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        txtBtnExit.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        txtBtnExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team1/image/imgExit.png"))); // NOI18N
        txtBtnExit.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtBtnExitMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                txtBtnExitMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                txtBtnExitMouseExited(evt);
            }
        });
        jPanel2.add(txtBtnExit, new org.netbeans.lib.awtextra.AbsoluteConstraints(267, 10, 40, -1));

        jLabel4.setCursor(Cursor.getPredefinedCursor(Cursor.HAND_CURSOR));
        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 12)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(204, 204, 204));
        jLabel4.setText("<html>\n<body>\nBelum punya akun? <u style=\"color: rgb(60,139,182);\">Klik disini!</u>\n</body>\n</html>");
        jLabel4.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel4MouseClicked(evt);
            }
        });
        jPanel2.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 510, -1, -1));

        jLabel2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/team1/image/imgFrmLogin.png"))); // NOI18N
        jPanel2.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 310, 550));

        jPanel2.setBackground(new Color(0,0,0,0));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 320, 560));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void txtBtnExitMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnExitMouseEntered
        txtBtnExit.setIcon(new ImageIcon(getClass().getResource("/team1/image/imgExitEntr.png")));
    }//GEN-LAST:event_txtBtnExitMouseEntered

    private void txtBtnExitMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnExitMouseExited
        txtBtnExit.setIcon(new ImageIcon(getClass().getResource("/team1/image/imgExit.png")));
    }//GEN-LAST:event_txtBtnExitMouseExited

    private void txtBtnExitMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtBtnExitMouseClicked
        System.exit(0);
    }//GEN-LAST:event_txtBtnExitMouseClicked

    private void txtMasukMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMasukMouseEntered
        txtMasuk.setIcon(new ImageIcon(getClass().getResource("/team1/image/imgBLoginEntr.png")));
    }//GEN-LAST:event_txtMasukMouseEntered

    private void txtMasukMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMasukMouseExited
        txtMasuk.setIcon(new ImageIcon(getClass().getResource("/team1/image/imgBLogin.png")));
    }//GEN-LAST:event_txtMasukMouseExited
    
    private void eyeMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_eyeMouseClicked
        if (!showPass) {
            txtPass.setEchoChar((char)0);
            eye.setIcon(new ImageIcon(getClass().getResource("/team1/image/iconEyeShow.png")));
            eye.setToolTipText("Hide");
            showPass=!showPass;
        } else {
            txtPass.setEchoChar('\u25cf');
            eye.setIcon(new ImageIcon(getClass().getResource("/team1/image/iconEyeHide.png")));
            eye.setToolTipText("Show");
            showPass=!showPass;
        }
    }//GEN-LAST:event_eyeMouseClicked

    private void txtMasukMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtMasukMouseClicked
        onLogin();
    }//GEN-LAST:event_txtMasukMouseClicked

    private void jLabel4MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel4MouseClicked
        String url="www.pnp.ac.id";
        try {
            java.awt.Desktop.getDesktop().browse(java.net.URI.create(url));
        } catch (IOException ex) {
            Logger.getLogger(Login.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jLabel4MouseClicked

    private void txtUnameKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtUnameKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            onLogin();
        }
    }//GEN-LAST:event_txtUnameKeyPressed

    private void txtPassKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPassKeyPressed
        if(evt.getKeyCode()==KeyEvent.VK_ENTER){
            onLogin();
        }
    }//GEN-LAST:event_txtPassKeyPressed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Windows".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Login.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Login().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel eye;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JLabel txtBtnExit;
    private javax.swing.JLabel txtMasuk;
    private javax.swing.JPasswordField txtPass;
    private javax.swing.JTextField txtUname;
    // End of variables declaration//GEN-END:variables
    
    private void onLogin(){
        if (uc.isLogin()) {
            Home h = new Home();
            h.setVisible(true);
            dispose();
        } else {
            JOptionPane.showMessageDialog(rootPane, "Akun tidak ditemukan");
        }
    }
}
